### ISSUE TITLE
Change target editing mechanics

### ISSUE THREAD

**Issue by l2zou** [BattleMage0231/Stalkpixel#5]
Instead of passing in terminal arguments as flags in order to edit your list of targets, the application should open your default editor instead.

This can be accomplished with the 'open' node module. 

```node
let open = require('open');

(async() => {
    open('a.txt', {'wait': true});
})();
```

**Comment by BattleMage0231** [comment]
Added in f3317b397a1894913d4c9b915f36d1cbe4983bf8
